Update detector_max to resolve CCD16 issue
Until now, we mapped detector IDs, numbers, and HDUs for VIRCAM
images, but in the calibrateImage step, CCD16 was missing from all
images due to the following error:

raise ValueError(f"Detector ID {detector_id} is out of bounds;
expected <{self._n_detectors}.")
ValueError: Detector ID 16 is out of bounds; expected <16.

Whit this commit, I updated "detector_max" in the "_instrument.py"
file to 17 (instead of 16), and this successfully resolved the issue.